dist: trusty
before_install:
  - sudo apt-get install -y ninja-build
script:
  - bash -x test.sh
  - cp Firmware/variants/1_75mm_MK3S-EINSy10a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK3S-EINSy10a-E3Dv6full variant failed" && false; }
  - cp firmware.hex 1_75mm_MK3S-EINSy10a-E3Dv6full.hex
  - cp Firmware/variants/1_75mm_MK3-EINSy10a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK3-EINSy10a-E3Dv6full variant failed" && false; }
  - cp firmware.hex 1_75mm_MK3-EINSy10a-E3Dv6full.hex
  - cp Firmware/variants/1_75mm_MK25S-RAMBo13a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK25S-RAMBo13a-E3Dv6full variant failed" && false; }
  - cp firmware.hex 1_75mm_MK25S-RAMBo13a-E3Dv6full.hex
  - cp Firmware/variants/1_75mm_MK25S-RAMBo10a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK25S-RAMBo10a-E3Dv6full variant failed" && false; }
  - cp firmware.hex 1_75mm_MK25S-RAMBo10a-E3Dv6full.hex
  - cp Firmware/variants/1_75mm_MK25-RAMBo13a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK25-RAMBo13a-E3Dv6full variant failed" && false; }
  - cp firmware.hex 1_75mm_MK25-RAMBo13a-E3Dv6full.hex
  - cp Firmware/variants/1_75mm_MK25-RAMBo10a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK25-RAMBo10a-E3Dv6full variant failed" && false; }
  - cp firmware.hex 1_75mm_MK25-RAMBo10a-E3Dv6full.hex
before_deploy:
  - cd /home/travis/build/vertigo235/Prusa-Firmware/lang
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 
    - '1_75mm_MK3S-EINSy10a-E3Dv6full.hex'
    - '1_75mm_MK3-EINSy10a-E3Dv6full.hex'
    - '1_75mm_MK25S-RAMBo13a-E3Dv6full.hex'
    - '1_75mm_MK25S-RAMBo10a-E3Dv6full.hex'
    - '1_75mm_MK25-RAMBo13a-E3Dv6full.hex'
    - '1_75mm_MK25-RAMBo10a-E3Dv6full.hex'
  skip_cleanup: true
  on:
    all_branches: true
    tags: true