dist: trusty
before_install:
  - sudo apt-get install -y ninja-build
script:
  - bash -x test.sh
  - bash -x build.sh
before_deploy:
  - cd /home/travis/build/vertigo235/Prusa-Firmware/lang
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: 
    - 'firmware.hex'
  skip_cleanup: true
  on:
    all_branches: true
    tags: true